---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: kubishar-test
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: ianisharpratama/reactsample:frontend-$TRAVIS_BUILD_NUMBER
        imagePullPolicy: Always
        command: [ "echo", "SUCCESS" ]
      imagePullSecrets:
        - name: kubis-secret
