---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: kubishar-test
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
<<<<<<< HEAD
        image: ianisharpratama/reactsample:frontend-*
=======
        image: ianisharpratama/reactsample:frontend-148313045
>>>>>>> 3335582f9909c44a0e7d240d6b8b113b05f54bc1
        imagePullPolicy: Always
      imagePullSecrets:
      - name: kubis-secret
